### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Ackmard** [agnostic-apollo/Android-Docs#2]
I would like to apologize for saying this here but it's my only hope.

I have installed an app called VMOS Pro it's like a virtual machine for Android. But since Android 12 came out with the "limitations" on phantom processes they also use another app called VMOS assistant that requires wireless debugging access to somehow "fix" that. I would really appreciate it if you could help me understand what exactly it did to my phone and if I can reverse it. I tried asking around in the official support group they have on telegram but the only answer I got is that : "It should only affect VMOS Pro and not the whole system". I know you probably have better things to do but I really have no idea where else to go for this. Sorry for the inconvenience and thank for your time.

**Comment by agnostic-apollo** [comment]
Assuming that assistant app is modifying phantom process related settings, then run `adb shell "/system/bin/device_config get activity_manager max_phantom_processes"` and `adb shell "settings get global settings_enable_monitor_phantom_procs"`  to see if a custom value has been set to it. If it has, then set `32` for former and `true` for later.

https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#commands-to-disable-phantom-process-killing-and-tldr

**Comment by Ackmard** [comment]
Hello and sorry again for bothering, `adb shell "settings get global settings_enable_monitor_phantom_procs"` returns null, Is that normal? I'm on Android 12 btw. And what about device config sync?

**Comment by agnostic-apollo** [comment]
`null` is fine and `settings_enable_monitor_phantom_procs` doesn't exist on android 12 anyways. Device config sync is enabled by default. Read the docs...

**Comment by Ackmard** [comment]
I'm sorry once again but is there a chance of bricking my phone like that? Probably a stupid question. I checked and device config is disabled that's why I asked, and does the order of the commands matter?

**Comment by agnostic-apollo** [comment]
You question about brick is already answered in the docs. Disabling device config should ideally be done before the other.

**Comment by Ackmard** [comment]
I'm trying to enable/reset everything to default, Should I just run this `adb shell "/system/bin/device_config set_sync_disabled_for_tests none; /system/bin/device_config put activity_manager max_phantom_processes 32"` ? Really thanks for you time in advance.

**Comment by agnostic-apollo** [comment]
Yes

**Comment by Ackmard** [comment]
Really thanks, I was hopping if you could like test the app in a dev environment or something to see exactly what it changes cause I really don't have the means to do it myself but I guess it's too much trouble. I really appreciate your help and time and wish you the best.

**Comment by agnostic-apollo** [comment]
Welcome. I could, but I don't have time. If you have so many trust issues, best not install such closed source apps or give them adb access in future. You can factory reset if you are so worried.

**Comment by Ackmard** [comment]
Is a factory reset going to revert everything? Do you suggest I do this just in case before my phone gets an OS upgrade? Thanks again for your time.

**Comment by agnostic-apollo** [comment]
Ideally, it should.

**Comment by Ackmard** [comment]
I run the command, did a reboot and everything seems fine for now. Thanks once again.
