### ISSUE TITLE
ASOP instead of AOSP

### ISSUE THREAD

**Issue by JavkhlanK** [agnostic-apollo/Android-Docs#3]
Hi, I found a small typo where it says ASOP instead of AOSP in [this heading](https://github.com/agnostic-apollo/Android-Docs/blob/0393b9b68e2e7276eb1cfbf6a6bcbbf0b4a38887/en/docs/apps/processes/phantom-cached-and-empty-processes.md#ASOP).

**Comment by agnostic-apollo** [comment]
Thanks
